### ISSUE TITLE
[not huginn related] Description page sometimes shows a blank page 

### ISSUE THREAD

**Issue by WangQiru** [iosOctohub/feedback#2] opened 2018-02-06 01:28 UTC
Description does not load for some issue/pull.

Eg: https://github.com/huginn/huginn/issues/2208

![4b6618ea-6da0-4785-bafa-896abd5c8a50](https://user-images.githubusercontent.com/5896343/35837279-f086a6a2-0adc-11e8-9a7d-30b62d22e476.jpeg)

Env:
iPhone X
iOS 11.2.5

**Comment by WangQiru** [comment] 2018-02-06 01:50
Ironically, this issue includes this issue XD

**Comment by martinpucik** [comment] 2018-02-06 10:25
Thanks for the report @WangQiru!
I can't reproduce this, but I think this could be resolved in v1.2.1 as well as #1 
Please, let me know if the update fixed this.

**Comment by martinpucik** [comment] 2018-02-06 13:51
@WangQiru nope, found the issue, will be fixed in next release!

**Comment by kstrib** [comment] 2018-02-06 16:10
How and why am I seeing this?

**Comment by martinpucik** [comment] 2018-02-09 16:40
@WangQiru should be fixed in new version now!

**Closed by martinpucik** 2018-02-09 16:40 UTC
Labels: bug
